spring.application.name=idesign
spring.datasource.url=jdbc:mariadb://localhost:3306/idesign?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.profiles.include=private
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dnlsemtmf@gmail.com
spring.mail.password=jwmw qwrd okou ouyh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#스프링 파일 사용 크기 제한 10MB 로 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB